
language: c++
sudo: false

addons:
  apt:
    packages:
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  include:
    # GCC 6
    - os: linux
      env: CXX=g++-6
      compiler: gcc

script:
  CXX=g++-6 make all


